# Generated by Django 5.2.6 on 2025-10-29 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('signup', 'User Signup'), ('chat', 'Chat Message'), ('weather_query', 'Weather Query'), ('alert_view', 'Alert Viewed'), ('settings_change', 'Settings Changed'), ('map_view', 'Map Viewed'), ('api_call', 'API Call'), ('error', 'Error Occurred')], max_length=20)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activity_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='activity_lo_timesta_cd2ed1_idx'), models.Index(fields=['user', '-timestamp'], name='activity_lo_user_id_f065d0_idx'), models.Index(fields=['activity_type', '-timestamp'], name='activity_lo_activit_ff3122_idx')],
            },
        ),
    ]
