# Generated by Django 5.2.6 on 2025-10-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_userlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
