# Generated by Django 5.2.6 on 2025-11-01 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_userprofile_middle_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('response', models.TextField()),
                ('user_mentioned', models.CharField(blank=True, max_length=100, null=True)),
                ('weather_data', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_chat_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_chat_history',
                'ordering': ['-timestamp'],
            },
        ),
    ]
