# Generated by Django 5.2.6 on 2025-11-01 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_adminchathistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminchathistory',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
