# Generated by Django 5.2.6 on 2025-11-01 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0006_adminchathistory_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
